[2021-12-18 09:03:11,721] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T08:50:25.202871+00:00 [queued]>
[2021-12-18 09:03:11,732] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T08:50:25.202871+00:00 [queued]>
[2021-12-18 09:03:11,733] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:03:11,733] {taskinstance.py:1068} INFO - Starting attempt 3 of 3
[2021-12-18 09:03:11,734] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:03:11,756] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): pull_from_git> on 2021-12-18T08:50:25.202871+00:00
[2021-12-18 09:03:11,758] {standard_task_runner.py:52} INFO - Started process 82953 to run task
[2021-12-18 09:03:11,780] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'pull_from_git', '2021-12-18T08:50:25.202871+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmp6w236i_2', '--error-file', '/tmp/tmpnwb8ykbc']
[2021-12-18 09:03:11,784] {standard_task_runner.py:77} INFO - Job 42: Subtask pull_from_git
[2021-12-18 09:03:11,857] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.pull_from_git 2021-12-18T08:50:25.202871+00:00 [running]> on host airflowvm
[2021-12-18 09:03:12,037] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=pull_from_git
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T08:50:25.202871+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T08:50:25.202871+00:00
[2021-12-18 09:03:12,039] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 09:03:12,040] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/AlgorithmStudy_211124 pull']
[2021-12-18 09:03:12,053] {subprocess.py:75} INFO - Output:
[2021-12-18 09:03:12,364] {subprocess.py:79} INFO - Already up to date.
[2021-12-18 09:03:12,365] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 09:03:12,395] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=pull_from_git, execution_date=20211218T085025, start_date=20211218T090311, end_date=20211218T090312
[2021-12-18 09:03:12,430] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-18 09:03:12,470] {local_task_job.py:151} INFO - Task exited with return code 0
