[2021-12-18 11:12:34,657] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T11:12:28.565672+00:00 [queued]>
[2021-12-18 11:12:34,662] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T11:12:28.565672+00:00 [queued]>
[2021-12-18 11:12:34,663] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 11:12:34,663] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-18 11:12:34,663] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 11:12:34,676] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): mv_indicator_to_repo> on 2021-12-18T11:12:28.565672+00:00
[2021-12-18 11:12:34,677] {standard_task_runner.py:52} INFO - Started process 5648 to run task
[2021-12-18 11:12:34,682] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'mv_indicator_to_repo', '2021-12-18T11:12:28.565672+00:00', '--job-id', '104', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmp4x8y0l2g', '--error-file', '/tmp/tmp34cesu8f']
[2021-12-18 11:12:34,683] {standard_task_runner.py:77} INFO - Job 104: Subtask mv_indicator_to_repo
[2021-12-18 11:12:34,726] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T11:12:28.565672+00:00 [running]> on host airflowvm
[2021-12-18 11:12:34,843] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=mv_indicator_to_repo
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T11:12:28.565672+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T11:12:28.565672+00:00
[2021-12-18 11:12:34,847] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 11:12:34,848] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'mv /home/airflow/airflow/result/html/20211218.html /home/airflow/Test/rank.md']
[2021-12-18 11:12:34,856] {subprocess.py:75} INFO - Output:
[2021-12-18 11:12:34,862] {subprocess.py:79} INFO - mv: cannot stat '/home/airflow/airflow/result/html/20211218.html': No such file or directory
[2021-12-18 11:12:34,862] {subprocess.py:83} INFO - Command exited with return code 1
[2021-12-18 11:12:34,872] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-12-18 11:12:34,874] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=rank_update, task_id=mv_indicator_to_repo, execution_date=20211218T111228, start_date=20211218T111234, end_date=20211218T111234
[2021-12-18 11:12:34,937] {local_task_job.py:151} INFO - Task exited with return code 1
