[2021-12-18 16:06:55,111] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T16:06:51.751278+00:00 [queued]>
[2021-12-18 16:06:55,118] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T16:06:51.751278+00:00 [queued]>
[2021-12-18 16:06:55,119] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:06:55,119] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-18 16:06:55,119] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:06:55,134] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): mv_indicator_to_repo> on 2021-12-18T16:06:51.751278+00:00
[2021-12-18 16:06:55,135] {standard_task_runner.py:52} INFO - Started process 2812 to run task
[2021-12-18 16:06:55,140] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'mv_indicator_to_repo', '2021-12-18T16:06:51.751278+00:00', '--job-id', '129', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpy9sq79a0', '--error-file', '/tmp/tmphl4d8j27']
[2021-12-18 16:06:55,141] {standard_task_runner.py:77} INFO - Job 129: Subtask mv_indicator_to_repo
[2021-12-18 16:06:55,178] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.mv_indicator_to_repo 2021-12-18T16:06:51.751278+00:00 [running]> on host airflowvm
[2021-12-18 16:06:55,260] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=mv_indicator_to_repo
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T16:06:51.751278+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T16:06:51.751278+00:00
[2021-12-18 16:06:55,260] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 16:06:55,261] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'mv /home/airflow/airflow/result/html/20211218.html /home/airflow/Test/rank.md']
[2021-12-18 16:06:55,264] {subprocess.py:75} INFO - Output:
[2021-12-18 16:06:55,266] {subprocess.py:79} INFO - mv: cannot stat '/home/airflow/airflow/result/html/20211218.html': No such file or directory
[2021-12-18 16:06:55,267] {subprocess.py:83} INFO - Command exited with return code 1
[2021-12-18 16:06:55,272] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-12-18 16:06:55,274] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=rank_update, task_id=mv_indicator_to_repo, execution_date=20211218T160651, start_date=20211218T160655, end_date=20211218T160655
[2021-12-18 16:06:55,314] {local_task_job.py:151} INFO - Task exited with return code 1
