[2021-12-18 11:03:24,322] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T11:00:07.858161+00:00 [queued]>
[2021-12-18 11:03:24,328] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T11:00:07.858161+00:00 [queued]>
[2021-12-18 11:03:24,328] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 11:03:24,328] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-12-18 11:03:24,329] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 11:03:24,342] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): git_add> on 2021-12-18T11:00:07.858161+00:00
[2021-12-18 11:03:24,343] {standard_task_runner.py:52} INFO - Started process 3074 to run task
[2021-12-18 11:03:24,349] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'git_add', '2021-12-18T11:00:07.858161+00:00', '--job-id', '96', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpd_915klv', '--error-file', '/tmp/tmpoxevqthc']
[2021-12-18 11:03:24,350] {standard_task_runner.py:77} INFO - Job 96: Subtask git_add
[2021-12-18 11:03:24,388] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.git_add 2021-12-18T11:00:07.858161+00:00 [running]> on host airflowvm
[2021-12-18 11:03:24,512] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=git_add
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T11:00:07.858161+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T11:00:07.858161+00:00
[2021-12-18 11:03:24,513] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 11:03:24,513] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/Test/ add rank.md']
[2021-12-18 11:03:24,520] {subprocess.py:75} INFO - Output:
[2021-12-18 11:03:24,531] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 11:03:24,559] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=git_add, execution_date=20211218T110007, start_date=20211218T110324, end_date=20211218T110324
[2021-12-18 11:03:24,600] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-18 11:03:24,642] {local_task_job.py:151} INFO - Task exited with return code 0
