[2021-12-16 08:18:42,827] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-16T08:18:34.505499+00:00 [queued]>
[2021-12-16 08:18:42,841] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-16T08:18:34.505499+00:00 [queued]>
[2021-12-16 08:18:42,843] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-16 08:18:42,843] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-16 08:18:42,844] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-16 08:18:42,861] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-12-16T08:18:34.505499+00:00
[2021-12-16 08:18:42,867] {standard_task_runner.py:52} INFO - Started process 47078 to run task
[2021-12-16 08:18:42,884] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-12-16T08:18:34.505499+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpyu_x5wmo', '--error-file', '/tmp/tmpg_30zg_o']
[2021-12-16 08:18:42,885] {standard_task_runner.py:77} INFO - Job 21: Subtask is_api_available
[2021-12-16 08:18:42,984] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-12-16T08:18:34.505499+00:00 [running]> on host airflowvm
[2021-12-16 08:18:43,074] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-12-16T08:18:34.505499+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-16T08:18:34.505499+00:00
[2021-12-16 08:18:43,080] {http.py:101} INFO - Poking: api/
[2021-12-16 08:18:43,097] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me, Port: None, Schema: , Login: , Password: ***, extra: {}
[2021-12-16 08:18:43,104] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-12-16 08:18:43,536] {base.py:243} INFO - Success criteria met. Exiting.
[2021-12-16 08:18:43,544] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211216T081834, start_date=20211216T081842, end_date=20211216T081843
[2021-12-16 08:18:43,603] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-16 08:18:43,618] {local_task_job.py:151} INFO - Task exited with return code 0
