[2021-12-18 17:11:15,298] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_push 2021-12-18T17:10:00+00:00 [queued]>
[2021-12-18 17:11:15,306] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_push 2021-12-18T17:10:00+00:00 [queued]>
[2021-12-18 17:11:15,307] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 17:11:15,307] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-18 17:11:15,307] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 17:11:15,320] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): git_push> on 2021-12-18T17:10:00+00:00
[2021-12-18 17:11:15,321] {standard_task_runner.py:52} INFO - Started process 14718 to run task
[2021-12-18 17:11:15,326] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'git_push', '2021-12-18T17:10:00+00:00', '--job-id', '205', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpbu63srud', '--error-file', '/tmp/tmpx84mienx']
[2021-12-18 17:11:15,327] {standard_task_runner.py:77} INFO - Job 205: Subtask git_push
[2021-12-18 17:11:15,373] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.git_push 2021-12-18T17:10:00+00:00 [running]> on host airflowvm
[2021-12-18 17:11:15,465] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=git_push
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T17:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-18T17:10:00+00:00
[2021-12-18 17:11:15,466] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 17:11:15,467] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git --git-dir=/home/airflow/Test/.git/ --work-tree=/home/airflow/Test/.git/ push']
[2021-12-18 17:11:15,470] {subprocess.py:75} INFO - Output:
[2021-12-18 17:11:16,873] {subprocess.py:79} INFO - To https://github.com/nicework-jin/Test
[2021-12-18 17:11:16,874] {subprocess.py:79} INFO -    1693813..74d1c53  main -> main
[2021-12-18 17:11:16,888] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 17:11:16,929] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=git_push, execution_date=20211218T171000, start_date=20211218T171115, end_date=20211218T171116
[2021-12-18 17:11:16,946] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-18 17:11:16,960] {local_task_job.py:151} INFO - Task exited with return code 0
